version: "3.7"

# x-extension fields
x-env-file: &env_file
  env_file:
    - ./.env


x-base-service: &base_service_settings
  <<: *env_file
  command: python asgi.py
  build:
    context: .
    dockerfile: docker/Dockerfile
  tty: true
  stdin_open: true
  restart: always
  volumes:
    - .src/app/:/src/app


services:
  backend_reporter:
    <<: *base_service_settings
    ports:
      - 8000:8000
      - 8888:8888
    container_name: backend_reporter


networks:
  default:
    external:
      name: zeromq-network
